+incdir+verif/xx_lsu_lrq/tb
+define+TDT_MP_HINFO_WIDTH=17
+define+VL_WIDTH=8
+define+VSTART_WIDTH=7
+define+WK_PA_WIDTH=40
+define+WK_PA_WIDTH_40
+define+WK_VA_WIDTH=48
+define+WK_MA_WIDTH=40
+define+WK_LS_DCACHE_SINGLE_TAG_WIDTH=26
+define+WK_LS_DCACHE_SINGLE_LDTAG_WIDTH=27
+define+WK_LS_DCACHE_DOUBLE_LDTAG_WIDTH=54
+define+WK_LS_DCACHE_TRIPLE_LDTAG_WIDTH=81
+define+WK_LS_DCACHE_LDTAG_WIDTH=108
+define+WK_LS_DCACHE_LDTAG_BF_ECC_LENGTH=22
+define+WK_LS_DCACHE_LDTAG_DOUBLE_BF_ECC_LENGTH=44
+define+WK_LS_DCACHE_LDTAG_TRIPLE_BF_ECC_LENGTH=66
+define+WK_LS_DCACHE_LDTAG_QUADRUPLE_BF_ECC_LENGTH=88
verif/xx_lsu_lrq/tb/xx_lsu_lrq_deps.sv
srcs/xx_lsu_lrq_entry.sv
srcs/xx_lsu_lrq.sv
verif/xx_lsu_lrq/tb/xx_lsu_lrq_assertions.sv
verif/xx_lsu_lrq/tb/xx_lsu_lrq_tb.sv
