#!/usr/bin/env python3
"""Generate a SystemVerilog interface and named DUT connections.

The DUT uses a 258-port non-ANSI declaration. Keeping the generated files in
Git makes a VCS checkout immediately runnable, while ``--check`` prevents the
wrapper from drifting when the RTL port list changes.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ENV_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ENV_ROOT.parents[1]
DUT_PATH = REPO_ROOT / "srcs/xx_lsu_ld_ag.sv"
IF_PATH = ENV_ROOT / "tb/xx_lsu_ld_ag_if.sv"
CONNECT_PATH = ENV_ROOT / "tb/xx_lsu_ld_ag_connect.svh"


@dataclass(frozen=True)
class Port:
    name: str
    direction: str
    width: str


DECLARATION = re.compile(
    r"^\s*(input|output|inout)\s+"
    r"(?:(?:wire|reg|logic)\s+)?"
    r"(?:(\[[^;]+\])\s+)?"
    r"([A-Za-z_][A-Za-z0-9_$]*)\s*;"
)


def strip_line_comments(text: str) -> str:
    return re.sub(r"//.*", "", text)


def parse_header_ports(source: str) -> list[str]:
    start = source.index("module xx_lsu_ld_ag")
    header = source[start : source.index(");", start)]
    header = strip_line_comments(header)
    parameter_end = header.index(")(") + 2
    return [
        token.strip()
        for token in header[parameter_end:].split(",")
        if token.strip()
    ]


def parse_ports(source: str) -> list[Port]:
    declarations: dict[str, tuple[str, str]] = {}
    for line in source.splitlines():
        match = DECLARATION.match(line)
        if match:
            direction, width, name = match.groups()
            declarations.setdefault(name, (direction, width or ""))

    header_ports = parse_header_ports(source)
    missing = [name for name in header_ports if name not in declarations]
    if missing:
        raise ValueError(f"missing declarations for DUT ports: {', '.join(missing)}")
    if len(header_ports) != 258:
        raise ValueError(f"expected 258 DUT ports, found {len(header_ports)}")

    return [
        Port(name=name, direction=declarations[name][0], width=declarations[name][1])
        for name in header_ports
    ]


def render_interface(ports: list[Port]) -> str:
    lines = [
        "// Generated by tools/gen_dut_if.py; do not edit by hand.",
        "`ifndef XX_LSU_LD_AG_IF_SV",
        "`define XX_LSU_LD_AG_IF_SV",
        "",
        "interface xx_lsu_ld_ag_if #(",
        "  parameter int LSIQENTRY = 12,",
        "  parameter int VMBENTRY  = 8,",
        "  parameter int PC_LEN    = 15,",
        "  parameter int IID_WIDTH = 7,",
        "  parameter int VREG      = 6,",
        "  parameter int PREG      = 7",
        ");",
    ]
    for port in ports:
        width = f" {port.width}" if port.width else ""
        lines.append(f"  logic{width} {port.name};")

    lines.extend(
        [
            "",
            "  task automatic drive_idle();",
        ]
    )
    for port in ports:
        if port.direction == "input" and port.name not in {
            "forever_cpuclk",
            "ctrl_ld_clk",
        }:
            lines.append(f"    {port.name} = '0;")
    lines.extend(
        [
            "    cp0_lsu_dcache_en = 1'b1;",
            "    cp0_lsu_icg_en = 1'b1;",
            "    cp0_lsu_mm = 1'b1;",
            "    mmu_lsu_ca = 1'b1;",
            "  endtask",
            "",
            "endinterface",
            "",
            "`endif",
            "",
        ]
    )
    return "\n".join(lines)


def render_connections(ports: list[Port]) -> str:
    lines = ["// Generated by tools/gen_dut_if.py; do not edit by hand."]
    for index, port in enumerate(ports):
        comma = "," if index + 1 < len(ports) else ""
        lines.append(f"  .{port.name:<44} (bus.{port.name}){comma}")
    lines.append("")
    return "\n".join(lines)


def check_or_write(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            print(f"generated file is stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in generated files differ from the DUT",
    )
    args = parser.parse_args()

    ports = parse_ports(DUT_PATH.read_text(encoding="utf-8"))
    ok = check_or_write(IF_PATH, render_interface(ports), args.check)
    ok &= check_or_write(CONNECT_PATH, render_connections(ports), args.check)
    if ok:
        mode = "verified" if args.check else "generated"
        print(f"{mode} {len(ports)} xx_lsu_ld_ag ports")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
